### ISSUE TITLE
Error When Running frr_exporter.go

### ISSUE THREAD

**Issue by permitanyany** [tynany/frr_exporter#2]
Running into the following issue:

cumulus@leaf01:~/frr_exporter$ sudo /usr/local/go/bin/go run frr_exporter.go
# command-line-arguments
./frr_exporter.go:58:19: cannot use ne (type *collector.Exporters) as type "github.com/prometheus/client_golang/prometheus".Collector in argument to registry.Register:
	*collector.Exporters does not implement "github.com/prometheus/client_golang/prometheus".Collector (wrong type for Collect method)
		have Collect(chan<- "github.com/tynany/frr_exporter/vendor/github.com/prometheus/client_golang/prometheus".Metric)
		want Collect(chan<- "github.com/prometheus/client_golang/prometheus".Metric)

**Comment by tynany** [comment]
What version of Go are you using?

**Comment by tynany** [comment]
Please use `go build && ./frr_exporter` instead of `go run` -- `go run` has limited functionality and will not utilise the `vendor` folder. You can look at https://github.com/golang/go/issues/20406 for more information. 

Cheers

**Comment by tynany** [comment]
What version of Go are you using? 

Can you try `go build && ./frr_exporter`?

**Comment by permitanyany** [comment]
cumulus@leaf01:~$ go version
go version go1.10.2 linux/amd64

cumulus@leaf01:~/frr_exporter$ go build && ./frr_exporter
# _/home/cumulus/frr_exporter
./frr_exporter.go:58:19: cannot use ne (type *collector.Exporters) as type "github.com/prometheus/client_golang/prometheus".Collector in argument to registry.Register:
	*collector.Exporters does not implement "github.com/prometheus/client_golang/prometheus".Collector (wrong type for Collect method)
		have Collect(chan<- "github.com/tynany/frr_exporter/vendor/github.com/prometheus/client_golang/prometheus".Metric)
		want Collect(chan<- "github.com/prometheus/client_golang/prometheus".Metric)

**Comment by tynany** [comment]
I am not able to replicate this issue. In the below, I run a Go 1.10.2 Docker container, pull down the repo and successfully build the project.

```
$ docker run --rm -it golang:1.10.2-stretch bash
root@32f00777abd7:/go# go version
go version go1.10.2 linux/amd64
root@32f00777abd7:/go# mkdir -p src/github.com/tynany && cd src/github.com/tynany
root@32f00777abd7:/go/src/github.com/tynany# git clone https://github.com/tynany/frr_exporter
Cloning into 'frr_exporter'...
remote: Enumerating objects: 703, done.
remote: Total 703 (delta 0), reused 0 (delta 0), pack-reused 703
Receiving objects: 100% (703/703), 1.03 MiB | 268.00 KiB/s, done.
Resolving deltas: 100% (313/313), done.
root@32f00777abd7:/go/src/github.com/tynany# cd frr_exporter/
root@32f00777abd7:/go/src/github.com/tynany/frr_exporter# go build && ./frr_exporter
INFO[0000] Starting frr_exporter (version=, branch=, revision=) on :9342  source="frr_exporter.go:92"
```

Can you please provide more details, especially about your Go environment?

If you aren't looking to make any code changes, you can always download the ready to use binaries from the releases page -- https://github.com/tynany/frr_exporter/releases.

**Comment by permitanyany** [comment]
Thanks, I ended up using the binary from the release page and that worked without issues.
