### ISSUE TITLE
Allow to set additional vtysh options

### ISSUE THREAD

**Issue by sc0rp10** [tynany/frr_exporter#39]
Hi, 

We plan to use this exporter in production to monitor our BGP infrastructure, but we need to use it as a docker container. With current architecture this is not possible because of exporter using local vtysh binary with hard-coded options.

My proposal is pack vtysh together with frr_exporter binary in docker image and allow to set some vtysh options as a exporter argument.
In my case additional arguments are `vtysh --config_dir / tmp --vty_socket / run / frr` and option may looks like` --frr.vtysh.options = "- config_dir / tmp --vty_socket / run / frr"`. This will allow use host-machine's vty socket and frr configs inside a docker container.

What do you think about it @tynany?

**Comment by tynany** [comment]
I have just implemented this feature in [v0.1.18](https://github.com/tynany/frr_exporter/releases/tag/v0.2.18), and a Docker container is now available via Dockerhub -- [tynany/frr_exporter](https://hub.docker.com/r/tynany/junos_exporter).

Let me know if you run into any issues. Cheers

**Comment by age9990** [comment]
I tried the docker container in our environment. However, there is no vtysh binary file in the container. Therefore, I mount the binary file from the host machine. Still, the exporter is not working functional since a lot of frr dependent libraries are not in the containers either. What should I do to correctly collect frr metrics from a container?

**Comment by tynany** [comment]
That is a good point. I've rebuilt the `frr_exporter` container from the `frrouting/frr` container which includes `vtysh` and all required dependencies. Please try again using `tynany/frr_exporter:v0.2.19` and let me know how you go.

**Comment by age9990** [comment]
> That is a good point. I've rebuilt the `tynany/frr_exporter` container from the `frrouting/frr` container, which includes `vtysh` and all required dependencies. Please try again using `tynany/frr_exporter:v0.2.19` and let me know how you go.

It worked like a charm. Appreciated.
