### ISSUE TITLE
Add AS number as a label in bgp metrics?

### ISSUE THREAD

**Issue by ShujieDev** [tynany/frr_exporter#4]
Hi, I'm interested in adding AS number as a label in bgp metrics. 
It would be more convenient for organizations that has hundreds of BGP sessions.

I already tested to adding few lines into the code and now it shows asn correct.
frr_bgp_message_input_total{address_family="ipv4unicast",asn="****",peer="33.34.45.67",vrf="default"} 23

Another way is that makiing AS number a metrics since it's integer.

Which way do you think is more effective?

If it's ok to add this feature, I can make a pull request for it.

**Comment by tynany** [comment]
I have added this feature to release v0.1.2 -- https://github.com/tynany/frr_exporter/releases/tag/v0.1.2.

**Comment by tynany** [comment]
I have added the labels `local_as` and `remote_as` to release v0.1.2 -- https://github.com/tynany/frr_exporter/releases/tag/v0.1.2.

Let me know if this covers what you are after.

**Comment by ShujieDev** [comment]
Looks great. Thank you!
