### ISSUE TITLE
github.com/prometheus/common/log was removed

### ISSUE THREAD

**Issue by skorpy2009** [tynany/frr_exporter#40]
Hi @tynany 

In the following commit the github.com/prometheus/common/log was removed so updating the dependencies is currently not possible. The logging system needs love :) 
https://github.com/prometheus/common/commit/a184d5b1dbe0c2249407d6cde3c866340c2ee2d2

**Comment by tynany** [comment]
I've just fixed this in the latest version of master. Summary of the [commit](https://github.com/tynany/frr_exporter/commit/b0e1b52a0cffc158e77c0b08d0af05ccedb73203):
 - Updated Go to version 1.17.
 - Updated all modules.
 - Moved logging to `github.com/prometheus/common/promlog`.

Thanks!

**Comment by skorpy2009** [comment]
Hey that was also my intention :D
Thank you!
