### ISSUE TITLE
Export advertised BGP routes as metric

### ISSUE THREAD

**Issue by sc0rp10** [tynany/frr_exporter#44]
Hi,
It would be nice, if frr_exporter can be able to export advertised-routes as metric from the `show ip bgp neighbor x.x.x.x advertised-routes` command. 
It will be useful for monitoring advertising which may be admin-down or wrongly configured.
What do you think @tynany ?

**Comment by tynany** [comment]
@sc0rp10 this feature is already supported. You can read more [here](https://github.com/tynany/frr_exporter#bgp-advertised-prefixes-to-a-peer).

tl;dr the metric you are looking for exists as `frr_bgp_prefixes_advertised_count_total`. If you are running FRR version 8.2+ it is enabled by default. For older versions of FRR, you need to enable frr_exporter's `--collector.bgp.advertised-prefixes` flag.
