### ISSUE TITLE
frr_exporter is not concurrency-safe

### ISSUE THREAD

**Issue by dswarbrick** [tynany/frr_exporter#47]
Whilst investigating #45, it suddenly became rather obvious that none of the collectors in frr_exporter is safe in the event of concurrent scrapes by multiple Prometheus instances (such as is recommended for fault tolerant setups).

Each collector uses a global errors slice, which is initialized to an empty slice in the collector's `Collect()` method, e.g.
```go
var (
    bgpErrors           = []error{}
)

// Collect implemented as per the prometheus.Collector interface.
func (c *BGPCollector) Collect(ch chan<- prometheus.Metric) {
    bgpErrors = []error{}
    collectBGP(ch, "ipv4")
}
```
If another scrape is still in progress, that global `bgpErrors` variable is racy. This is likely what is causing the intermittent segfaults and unexplained nil pointers in our environment, where we have two Prometheus instances configure to scrape identical targets.

The docs for the prometheus.Collector interface type are clear about concurrency:
```go
type Collector interface {
	...
	// Collect is called by the Prometheus registry when collecting
	// metrics. ...
	//
	// This method may be called concurrently and must therefore be
	// implemented in a concurrency safe way. Blocking occurs at the expense
	// of total performance of rendering all registered metrics. Ideally,
	// Collector implementations support concurrent readers.
	Collect(chan<- Metric)
}
```

I suspect that fixing this is going to require some non-trivial changes to the code.

**Comment by tynany** [comment]
Hey @dswarbrick , thank you for contributing!

You are right. I have been working on a refactor as the code has many nuances like this one that I am unhappy with. This issue is the icing on the cake -- I will finish the refactor today.

**Comment by dswarbrick** [comment]
@tynany Thanks for the quick response. It's good to know that you have already been working on refactoring the code, because I was about to go down that path with a PR myself.

I have written a couple of inhouse / proprietary exporters where I work, which are based heavily on the design of node_exporter. Each (sub-)collector registers a factory function in a map, which are used to construct the collector. The sub-collectors conform to an interface:
```go
// Collector is the interface a collector has to implement.
type Collector interface {
	Update(ch chan<- prometheus.Metric) error
}
```
The factory function has the signature `func(log.Logger) (Collector, error)`, so each `Collector` has a `log.Logger` passed to it, which can be used for e.g. emitting error messages directly, during a scrape. This would get around what you have currently implemented with the global error slices.

The main collector (i.e., which implements `prometheus.Collector`) iterates over a map of these `Collector`s, calling their `Update` method, which emits the metrics directly to the provided channel. Since the `Update` method returns an error, you could use this to determine the value for the `frrCollectorUp` metric.

I thoroughly recommend following this design, since it eliminates a lot of headaches and is quite flexible and easy to add new collectors to in future.

**Comment by tynany** [comment]
You took the words right out of my mouth :D The refactor I have been working on is indeed based on node exporter. I have already implemented the same refactor in some of the other exporters I have created (e.g. https://github.com/tynany/cumulus_exporter), but have sadly been taking my time with frr exporter.

Thank you!

**Comment by dswarbrick** [comment]
That's awesome news, I look forward to seeing the new, improved frr_exporter when you're done!

**Comment by tynany** [comment]
Just an update here -- as with most things, finding time has been challenging. The refactor is complete, I just need to validate and tidy it up before pushing.

**Comment by bdrung** [comment]
How about pushing the current state to a branch for review?

**Comment by k0ste** [comment]
@tynany, can you bump release please, when all code landed to master? Thanks!

**Comment by tynany** [comment]
@dswarbrick here is the PR -- https://github.com/tynany/frr_exporter/pull/48. Please review at your earliest convenience.

@k0ste yep, I will bump to proper semantic versioning once https://github.com/tynany/frr_exporter/pull/48 has been merged.

**Comment by tynany** [comment]
@bdrung & @dswarbrick here is the PR -- https://github.com/tynany/frr_exporter/pull/48. Please review at your earliest convenience.

@k0ste yep, I will bump to proper semantic versioning once https://github.com/tynany/frr_exporter/pull/48 has been merged.

**Comment by bdrung** [comment]
Reviewed and commented #48. This PR addresses all smelly parts of the code and will make the code concurrency-safe.
