### ISSUE TITLE
frr_exporter still try to collect bgp data even bgp/bgp6 collector been disabled

### ISSUE THREAD

**Issue by ShujieDev** [tynany/frr_exporter#5]
Hi Tynany,

I found the exporter is still try to get bgp information when I disabled bgp collectors.

It leaves lots of spam in the frr log as the following.
ERRO[0013] collector "bgp6" scrape failed: cannot unmarshal bgp summary json: unexpected end of JSON input  source="collector.go:132"
ERRO[0013] collector "bgp" scrape failed: cannot unmarshal bgp summary json: unexpected end of JSON input  source="collector.go:132

Could you possible fix it?

Thanks a lot!
Shujie

**Comment by tynany** [comment]
I am not able to reproduce this behaviour. Can you please confirm you are running frr_exporter with the `--no-collector.bgp` and `--no-collector.bgp6` flags? Example:

```./frr_exporter --no-collector.bgp --no-collector.bgp6```

**Comment by tynany** [comment]
Closing this issue due to the lack of response from the reporter.
