### ISSUE TITLE
Possible freebsd support?

### ISSUE THREAD

**Issue by LaurentDumont** [tynany/frr_exporter#66]
Hiya!

I'm looking to get this running on Pfsense, which is based around FreeBSD.  It can run FRR natively, but SNMP doesn't expose BGP data.

- Because BSD != Linux, the Go binary doesnt work.
```
[2.5.2-RELEASE][admin@pfSense.localdomain]/root/frr_exporter-1.1.0.linux-amd64: file frr_exporter 
frr_exporter: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=j-uoBu0kvj9N9iU6S4WE/wUB1coaxE8Ovw-9W0HY7/TZNeZIlTy7x2Eq-huA7I/pBehHD21XjCwDpcXTc0a, not stripped
```
- Pfsense cannot run Docker so a container is a no go :(

Couple of options

- FreeBSD go binaries? No idea if that is even feasible.
- Connecting to the socket remotely? If we are using the `vtysh` and could configure ssh less access, that could work?

**Comment by tynany** [comment]
Thanks for the detailed info. I will take a look at this in the coming week. Cheers

**Comment by tynany** [comment]
Apologies for taking so long. Freebsd binaries are now included when building and are available starting from [v1.1.1](https://github.com/tynany/frr_exporter/releases/tag/v1.1.1).

**Comment by LaurentDumont** [comment]
Woohoo!

It's alive!

```
frr_bgp_peer_prefixes_received_count_total{afi="ipv4",local_as="399944",peer="123.123.123.123",peer_as="13213",safi="unicast",vrf="default"} 0
frr_bgp_peer_prefixes_received_count_total{afi="ipv4",local_as="399944",peer="124.124.124.124",peer_as="66666",safi="unicast",vrf="default"} 0
frr_bgp_peer_prefixes_received_count_total{afi="ipv4",local_as="399944",peer="170.39.196.221",peer_as="33185",safi="unicast",vrf="default"} 1
frr_bgp_peer_prefixes_received_count_total{afi="ipv4",local_as="399944",peer="42.42.42.42",peer_as="4242",safi="unicast",vrf="default"} 0
```

Thank you!

**Comment by LaurentDumont** [comment]
I didn't see a donate/contribute but let me know if I can send some $ your way. :)

**Comment by tynany** [comment]
@LaurentDumont Awesome! Glad it's working.
