### ISSUE TITLE
Add peer description to the labels

### ISSUE THREAD

**Issue by perkons** [tynany/frr_exporter#7]
Could you please add peer description to the metric labels like this:
`frr_bgp_peer_up{address_family="ipv4unicast",peer_descr="some_neighbor",local_as="65550",peer="10.1.2.3",peer_as="58888",vrf="internet"} 1`

You can usually get the description by running:
`# vtysh -c " show run " | grep description`

I know that you are using the json format and there is no description in the json output. I am not sure how this could be implemented.

For us this is important as we need to see the neighbour name in the alerts.

**Comment by tynany** [comment]
Generally, you do not want to use labels for anything susceptible to frequent change (e.g. descriptions) as different label values + metric name combinations create entirely different metrics, but I can see the value from your point of view. I will work on adding a feature that allows your use case via a flag, such as `--bgp.descriptions`.

**Comment by perkons** [comment]
I totally agree. I know that with label changes we will get new time series. However, in our case the descriptions do not change and are the neighbour names. To use a flag for this is a good idea. Thank you very much.

**Comment by tynany** [comment]
This feature is now supported in v0.2.1. 

Release -- https://github.com/tynany/frr_exporter/releases/tag/v0.2.1
Readme -- https://github.com/tynany/frr_exporter#bgp-peer-description-labels

**Comment by perkons** [comment]
Thank you for the fast feature implementation. Unfortunately, this is not something our network team will accept. Would it be maybe possible to implement it so that the peer description must not be JSON formatted?
Instead of
`neighbor 192.168.0.1 description {"desc":"important peer"}`
use this configuration
`neighbor 192.168.0.1 description important peer`
I know that you are using type in the description and so, again I am not sure how this could be implemented and if you would be willing to do it.

**Comment by tynany** [comment]
This is now supported in v0.2.2 using the `--collector.bgp.peer-descriptions.plain-text` flag. Let me know if this satisfies what you are after. Thanks for the feature request!

**Comment by perkons** [comment]
Awesome, thank you for your time and effort, much appreciated.
