### ISSUE TITLE
Where is the counter "frr_bgp_rib_count_total" coming from?

### ISSUE THREAD

**Issue by 33Fraise33** [tynany/frr_exporter#70]
Hello,

We are having an issue with the `rr_bgp_rib_count_total` counter. We are peering with an uplink provider and in the received routes we are seeing that the received routes in our vrf is not matching with the rib routes. 
See screenshot below:
![image](https://user-images.githubusercontent.com/6802744/167378275-3408823c-cf20-422d-9484-19db48afec64.png)

What query is being used to calculate the rib routes? I have checked the code but I am not completely understanding it unfortunately.

**Comment by tynany** [comment]
Hello, the `frr_bgp_rib_count_total` gauge comes from the `ribCount` field of `show bgp vrf all ipv4 unicast summary json`. You can also see the human-readable value using `show bgp vrf all ipv4 unicast summary`.

I have confirmed the values match in my test environment:
```
# HELP frr_bgp_rib_count_total Number of routes in the RIB.
# TYPE frr_bgp_rib_count_total gauge
frr_bgp_rib_count_total{afi="ipv4",local_as="64800",safi="unicast",vrf="default"} 13
```

```
switch1# sh bgp sum
< OMITTED TEXT >
RIB entries 13, using 1976 bytes of memory
````

Is there only one peer (the one with ~889k received prefixes)? If so, it does seem strange there are approx double the number of routes in the RIB. Is ECMP coming into play here? Can you please show me the output of `sh bgp sum vrf all`?

**Comment by 33Fraise33** [comment]
Hello,

I just confirmed, running: the command you provided in my personal test environment gives me the same result:
```
kingpin# show bgp vrf all ipv6 unicast summary 
BGP router identifier 193.148.249.106, local AS number 211184 vrf-id 0
BGP table version 159336
RIB entries 285185, using 50 MiB of memory
Peers 1, using 723 KiB of memory
Peer groups 1, using 64 bytes of memory

Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
2a0c:9a40:1::1  4      34927    119381        30        0    0    0 00:08:27       150841        1 IFOG PEERING
```
Exporter: 
```
# TYPE frr_bgp_rib_count_total gauge
frr_bgp_rib_count_total{afi="ipv6",local_as="211184",safi="unicast",vrf="default"} 285208
```

This is running the latest frr_exporter version: 
```
# HELP frr_exporter_build_info A metric with a constant '1' value labeled by version, revision, branch, and goversion from which frr_exporter was built.
# TYPE frr_exporter_build_info gauge
frr_exporter_build_info{branch="HEAD",goversion="go1.17.5",revision="5ac721e047f91e8906ece32ac2ff62797e2a5d6a",version="1.1.0"} 1
```

with the latest frr version: `FRRouting (version 8.2.2)`
