### ISSUE TITLE
New docker image for frr_exporter v1.1.1?

### ISSUE THREAD

**Issue by posiczko** [tynany/frr_exporter#78]
Hello,

There appears to be a new release of frr_exporter, 1.1.1 which fixes the resource leak mentioned in #63. That release does not have a corresponding [docker image](https://hub.docker.com/r/tynany/frr_exporter/tags). Any chance for an official build with tag 1.1.1?

Thank you!

Pawel

**Comment by tynany** [comment]
Thanks for that. I've pushed v1.1.1, although, v1.1.2 has just been released with a couple of bug fixes.
