### ISSUE TITLE
BGP peer descriptions in plain text not added as labels to the metrics

### ISSUE THREAD

**Issue by perkons** [tynany/frr_exporter#8]
I am already trying out the new feature, the flag --collector.bgp.peer-descriptions.plain-text and it is not working for me. I have tried the exporter on 3 different hosts and none of them are showing the peer_descr label.
I run the exporter like this:
`# ./frr_exporter --collector.bgp.peer-descriptions.plain-text --no-collector.ospf`

Output of `vtysh -c "show run bgp`:
```
router bgp 64512 vrf internet
 bgp router-id 192.168.0.180
 neighbor 192.168.0.1 remote-as 64555
 neighbor 192.168.0.1 description importantpeer
 neighbor 192.168.0.2 remote-as 64555
 neighbor 192.168.0.2 description importantpeer1
 neighbor 192.168.0.3 remote-as 64512
 neighbor 192.168.0.3 description importantpeer2
 neighbor 192.168.0.3 bfd
```

These are the metrics:

```
frr_bgp_peer_state{afi="ipv4",local_as="64512",peer="192.168.0.1",peer_as="64555",safi="unicast",vrf="internet"} 1
frr_bgp_peer_state{afi="ipv4",local_as="64512",peer="192.168.0.2",peer_as="64555",safi="unicast",vrf="internet"} 1
frr_bgp_peer_state{afi="ipv4",local_as="64512",peer="192.168.0.3",peer_as="64512",safi="unicast",vrf="internet"} 1
```

**Comment by tynany** [comment]
You will still need to pass the `--collector.bgp.peer-descriptions` flag to turn on descriptions. 

Expanding on your above execution command, you'd need:

`# ./frr_exporter --collector.bgp.peer-descriptions.plain-text --no-collector.ospf --collector.bgp.peer-descriptions`

**Comment by perkons** [comment]
Thank you very much. It is working with the right flags.
