### ISSUE TITLE
Updating modules

### ISSUE THREAD

**Issue by paketb0te** [tynany/frr_exporter#86]
Hi @tynany,

first of all, thanks for providing this exporter, it is very useful to us!

Would it be possible to update the used dependencies to their respective versions?

I built and tested the container sucessfully with the changes in [5dcdd911](https://github.com/paketb0te/frr_exporter/commit/5dcdd91116508fc7fec1bc3334e56ce7db351ab5) (just ran `go get -u && go mod tidy`). Please let me know if I should open a PR :)

**Comment by tynany** [comment]
Hi @paketb0te,

Please feel free to open a PR; otherwise, I'll take a look in a couple of days.

Cheers,
Tynan
