### ISSUE TITLE
How to use the exporter when running frr in container also

### ISSUE THREAD

**Issue by MartijnStraatman** [tynany/frr_exporter#93]
Hi,

We are planning to use Frr and run it inside a container. Metrics are crucial for us. How can I  access the metrics when frr is running in a container and this exporter also.

**Comment by paketb0te** [comment]
We used to do this by creating a shared volume that gets mounted into both the FRR container and the exporter container, and then place the control socket there.

Nowadays we run k8s so we just stick both containers into the same pod.

**Comment by MartijnStraatman** [comment]
Ok, thx !
