### ISSUE TITLE
Push images to a different registry

### ISSUE THREAD

**Issue by onedr0p** [tynany/frr_exporter#99]
Given the recent dockerhub announcement of removing free team orgs, I'm wondering if the current org will be affected? And if so perhaps this could have a high priority? There are other options to use like GHCR or Quay.

https://github.com/docker/hub-feedback/issues/2314

**Comment by tynany** [comment]
https://hub.docker.com/r/tynany/frr_exporter is under my personal user account and will not be affected afaik. I am happy to push to another registry such as GHCR or Quay if this is something you'll find useful.

**Comment by onedr0p** [comment]
GHCR would be awesome because Docker still has strict limitations on retention and pull rate limits.

**Comment by tynany** [comment]
The container is now available in GHCR from release v1.2.0 onwards. Please open another issue if you need a previous release uploaded.
